FROM php:8.1.0-fpm
WORKDIR "/application"

COPY --from=composer /usr/bin/composer /usr/bin/composer
COPY docker/php/php.ini /usr/local/etc/php/php.ini
COPY docker/php/opcache.ini /usr/local/etc/php/conf.d/opcache.ini

RUN apt-get update && \
    apt-get install --yes \
        git \
        libzip-dev \
        zip \
        libicu-dev \
    && docker-php-ext-install \
        opcache \
        zip \
        mysqli \
        pdo_mysql \
        intl
