FROM php:8.1.0-fpm
WORKDIR "/application"

COPY --from=composer /usr/bin/composer /usr/bin/composer

RUN apt-get update && \
    apt-get install --yes \
        git \
        libzip-dev \
        zip \
        libicu-dev \
    && docker-php-ext-install \
        zip \
        mysqli \
        pdo_mysql \
        intl \
    && rm -rf /var/lib/apt/lists/* \
    && pecl install \
        xdebug \
        redis \
    && docker-php-ext-enable \
        xdebug \
        redis \
    && php artisan migrate:fresh --seed
